//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Home</summary>
	[PublishedContentModel("home")]
	public partial class Home : PublishedContentModel, IContentPage, IFrontpage, ISEO
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "home";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Company name
		///</summary>
		[ImplementPropertyType("companyName")]
		public string CompanyName
		{
			get { return this.GetPropertyValue<string>("companyName"); }
		}

		///<summary>
		/// Facebook link
		///</summary>
		[ImplementPropertyType("facebookLink")]
		public Umbraco.Web.Models.RelatedLinks FacebookLink
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("facebookLink"); }
		}

		///<summary>
		/// Footer text
		///</summary>
		[ImplementPropertyType("footerText")]
		public string FooterText
		{
			get { return this.GetPropertyValue<string>("footerText"); }
		}

		///<summary>
		/// Linkedin link
		///</summary>
		[ImplementPropertyType("linkedinLink")]
		public Umbraco.Web.Models.RelatedLinks LinkedinLink
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("linkedinLink"); }
		}

		///<summary>
		/// Logo
		///</summary>
		[ImplementPropertyType("logo")]
		public Umbraco.Web.Models.ImageCropDataSet Logo
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("logo"); }
		}

		///<summary>
		/// Twitter link
		///</summary>
		[ImplementPropertyType("twitterLink")]
		public Umbraco.Web.Models.RelatedLinks TwitterLink
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("twitterLink"); }
		}

		///<summary>
		/// Website icon
		///</summary>
		[ImplementPropertyType("websiteIcon")]
		public Umbraco.Web.Models.ImageCropDataSet WebsiteIcon
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("websiteIcon"); }
		}

		///<summary>
		/// Website name
		///</summary>
		[ImplementPropertyType("websiteName")]
		public string WebsiteName
		{
			get { return this.GetPropertyValue<string>("websiteName"); }
		}

		///<summary>
		/// Body text
		///</summary>
		[ImplementPropertyType("bodyText")]
		public IHtmlString BodyText
		{
			get { return Umbraco.Web.PublishedContentModels.ContentPage.GetBodyText(this); }
		}

		///<summary>
		/// Headline
		///</summary>
		[ImplementPropertyType("headline")]
		public string Headline
		{
			get { return Umbraco.Web.PublishedContentModels.ContentPage.GetHeadline(this); }
		}

		///<summary>
		/// Banner image
		///</summary>
		[ImplementPropertyType("bannerImage")]
		public Umbraco.Web.Models.ImageCropDataSet BannerImage
		{
			get { return Umbraco.Web.PublishedContentModels.Frontpage.GetBannerImage(this); }
		}

		///<summary>
		/// Countdown
		///</summary>
		[ImplementPropertyType("countdown")]
		public DateTime Countdown
		{
			get { return Umbraco.Web.PublishedContentModels.Frontpage.GetCountdown(this); }
		}

		///<summary>
		/// Meta description
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetMetaDescription(this); }
		}

		///<summary>
		/// Meta title
		///</summary>
		[ImplementPropertyType("metaTitle")]
		public string MetaTitle
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetMetaTitle(this); }
		}
	}
}
