//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Schedule card</summary>
	[PublishedContentModel("scheduleCard")]
	public partial class ScheduleCard : PublishedContentModel, ISEO
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "scheduleCard";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ScheduleCard(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ScheduleCard, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Card description: Description of your card
		///</summary>
		[ImplementPropertyType("cardDescription")]
		public IHtmlString CardDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("cardDescription"); }
		}

		///<summary>
		/// Card end
		///</summary>
		[ImplementPropertyType("cardEnd")]
		public DateTime CardEnd
		{
			get { return this.GetPropertyValue<DateTime>("cardEnd"); }
		}

		///<summary>
		/// Card start
		///</summary>
		[ImplementPropertyType("cardStart")]
		public DateTime CardStart
		{
			get { return this.GetPropertyValue<DateTime>("cardStart"); }
		}

		///<summary>
		/// Select room
		///</summary>
		[ImplementPropertyType("selectRoom")]
		public string SelectRoom
		{
			get { return this.GetPropertyValue<string>("selectRoom"); }
		}

		///<summary>
		/// Speaker: Enter speaker name
		///</summary>
		[ImplementPropertyType("speaker")]
		public string Speaker
		{
			get { return this.GetPropertyValue<string>("speaker"); }
		}

		///<summary>
		/// Meta description
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetMetaDescription(this); }
		}

		///<summary>
		/// Meta title
		///</summary>
		[ImplementPropertyType("metaTitle")]
		public string MetaTitle
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetMetaTitle(this); }
		}
	}
}
